### ISSUE TITLE
How to set the position to bottom right?

### ISSUE THREAD

**Issue by zhmiao** [jeisner93/ubersicht-binary-clock#1]
Hi. I tried to change the widget position in the index.coffee by changing the `top` and `left` to `bottom` and `right`. But it seems not working. I don't understand why.

**Comment by joeleisner** [comment]
Hey, ranranking!

Thanks for submitting this issue. I've gone ahead and located the problem with the CSS; the `top` and `left` styling were being applied to `.container`, as opposed to the whole widget. I've updated the widget to use global positioning, and now if you change `top` and `left` (located right at the top of the CSS) to `bottom` and `right`, you'll see that it now works as intended.

Again, thanks for submitting this issue. This issue will now be closed.

**Comment by joeleisner** [comment]
Hey, ranranking!

Thanks for submitting this issue. I've gone ahead and located the problem with the CSS; the `top` and `left` styling were being applied to `.container`, as opposed to the whole widget. I've updated the widget to use global positioning, and now if you change `top` and `left` (located right at the top of the CSS) to `bottom` and `right`, you'll see that it now works as intended.

Again, thanks for submitting this issue. This issue will now be closed.

**Comment by zhmiao** [comment]
Thank you very much for the help!

**Comment by joeleisner** [comment]
No problem! Enjoy the widget!
